KafkaClient {
  com.sun.security.auth.module.Krb5LoginModule required
  useTicketCache=false
  useKeyTab=true
  serviceName="kafka"
  storeKey=true
  debug=true
  keyTab="/etc/security/keytabs/kafka-consumer.keytab"
  principal="kafka/consumer@PULSAR.COM";
};

PulsarProducer {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   storeKey=true
   useTicketCache=false
   keyTab="/etc/security/keytabs/producer.keytab"
   principal="producer@PULSAR.COM"
   debug=true;
};