# Deserializer class for key that implements the org.apache.kafka.common.serialization.Deserializer interface.
key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# Deserializer class for value that implements the org.apache.kafka.common.serialization.Deserializer interface.
value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# broker server list
bootstrap.servers=localhost:9092
# The maximum amount of data the server should return for a fetch request
fetch.min.bytes= 52428800
# consumer group name
group.id.prefix=kafka_to_pulsar_task_

# The expected time between heartbeats to the   consumer coordinator when using Kafka's group management facilities.
heartbeat.interval.ms=3000

# The maximum amount of data per-partition the server will return.
max.partition.fetch.bytes=1048576

# The timeout used to detect client failures when using Kafka's group management facility.
session.timeout.ms=45000

# earliest, latest, none
auto.offset.reset=latest

# If true the consumer's offset will be periodically committed in the background.
enable.auto.commit=false

# Whether internal topics matching a subscribed pattern should be excluded from the subscription.
exclude.internal.topics=true

# The maximum amount of data the server should return for a fetch request. 50MB
fetch.max.bytes=52428800

# The maximum delay between invocations of poll() when using consumer group management.
max.poll.interval.ms=300000

# The maximum number of records returned in a single call to poll().
max.poll.records=100000

# The size of the TCP receive buffer (SO_RCVBUF) to use when reading data.
receive.buffer.bytes=65536

# The configuration controls the maximum amount of time the client will wait for the response of a request.
request.timeout.ms=30000

# Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL.
security.protocol=PLAINTEXT

# The maximum amount of time the server will block before answering the fetch request
# if there isn't sufficient data to immediately satisfy the requirement given by fetch.min.bytes.
fetch.max.wait.ms=500

#security.protocol=SASL_PLAINTEXT
#sasl.mechanism=GSSAPI
#sasl.kerberos.service.name=kafka

