# Deserializer class for key that implements the org.apache.kafka.common.serialization.Deserializer interface.
key.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
# Deserializer class for value that implements the org.apache.kafka.common.serialization.Deserializer interface.
value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
# broker server list
bootstrap.servers=localhost:9093
#The number of acknowledgments the producer requires the leader to have received before considering a request complete.
acks=1
# The producer will attempt to batch records together into fewer requests whenever multiple records are being sent to the same partition.
batch.size=10485760
# The producer groups together any records that arrive in between request transmissions into a single batched request.
linger.ms=20
# The total bytes of memory the producer can use to buffer records waiting to be sent to the server
buffer.memory=134217728
# The configuration controls how long the <code>KafkaProducer</code>'s <code>send()</code>, <code>partitionsFor()</code>
max.block.ms=1728000000
# The compression type for all data generated by the producer. The default is none (i.e. no compression), values are none, gzip, snappy, lz4, or zstd.
compression.type=lz4
# send timeout, 2day
delivery.timeout.ms=1728000000

# Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL.
#security.protocol=SASL_PLAINTEXT
#sasl.mechanism=GSSAPI
#sasl.kerberos.service.name=kafka
